#!/usr/bin/env python3

import json
import sys

USAGE = "forge_script_block_numbers <./broadcast/path/to/run-latest.json>"

if len(sys.argv) != 2:
    print(USAGE)
    exit()

with open(sys.argv[1]) as f:
    run_result = json.load(f)


last_block_number = None
for receipt in run_result["receipts"]:
    block_number = receipt["blockNumber"]
    if block_number == last_block_number:
        continue
    last_block_number = block_number
    print(block_number)
